In [8]:
import numpy as np
my_array=np.array([2,3,4,75,86,95],np.int64)
print(my_array)
print(my_array.dtype)
my_array[2]=45
print(my_array)

[ 2  3  4 75 86 95]
int64
[ 2  3 25 75 86 95]


In [12]:
import numpy as np
my_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_arr)
print(my_arr.dtype)
print(my_arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
9


In [16]:
zeros=np.zeros((2, 5))

In [17]:
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
#arrange()
rng=np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
#linspace
lspace=np.linspace(1,50,10)
print(lspace)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [20]:
ar=np.array([[1,2,3],[4,5,6]])
ar1=np.array([[1,2,3],[7,8,9]])
print(ar*ar1)

[[ 1  4  9]
 [28 40 54]]
